project:
  type: website
  output-dir: docs

website:
  title: "Yi-Hsin"
  navbar:
    left:
      - href: https://yihsinlu.github.io/yhlu.io/Website/index.html
        text: Home
      - text: About Me
        menu: 
          - href: Contact.qmd
            text: Contact Me
          - href: https://github.com/YiHsinLu
            text: Github
          - href: diary.qmd
            text: Working Diary
      
      - text: R tutorial
        menu: 
          - href: Rtutorial.qmd
            text: 0 Basic R
          - href: Data.qmd
            text: 1 Data Processing
          - href: Visual.qmd
            text: 2 Data Visualization

    


format:
  html:
    theme: 
      light: mode_light.scss
      dark: mode_dark.scss
    css: styles.css
    toc: true

editor: visual

