```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(ggrepel)
library(ggforce)
library(glmnet)
library(survival)
library(rms)
library(MASS)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tableone)
library(kableExtra)
library(tidyverse)
library(data.table)
library(knitr)
library(kableExtra)
library(naniar)
library(curl)
library(tableone)
library(MatchIt)
library(WeightIt)
library(survey)
library(PSweight)
library(cobalt)
library(broom)
library(PSweight)
library(glmnet)
library(survminer)
library(CalibrationCurves)
library(pmcalibration)
library(prodlim)
library(lava)
library(riskRegression)
library(pec)
library(finalfit)
library(ggfortify)
library(ggpubr)
library(GGally)
library(mltools)
library(jaccard)
library(qvalue)
library(MixGHD)
data('banknote')
```

```{r}
pcaDf = prcomp(t(banknote[,-1]),
               center = TRUE,
               retx = T)

visualpca = pcaDf$rotation[,1:3]

colnames(visualpca) = c('pc1', 'pc2', 'pc3')
visualpca = as.data.frame(visualpca)

visualpca = transform(visualpca, 
                      pc1 = as.numeric(pc1),
                      pc2 = as.numeric(pc2),
                      pc3 = as.numeric(pc3))
```

```{r}
swissbank_pca <- plot_ly(data = visualpca, x = ~pc1, y = ~pc2, color = banknote$Status)
```


```{r}
hist(New_df$Height,
     nclass = 20,
     main = "Height",
     xlab = "height (cm)",
     ylab = "N")
```

```{r}
p1 <- hist(BMI_M, nclass = 15)                     # centered at 4
p2 <- hist(BMI_F, nclass = 20)                     # centered at 6
plot( p1, col=rgb(0,0,1,1/4), xlim=c(10,30))  # first histogram
plot( p2, col=rgb(1,0,0,1/4), xlim=c(10,30), add=T)  # second
```


```{r}
heightM <- New_df%>%filter(Gender=="M")
heightF <- New_df%>%filter(Gender=="F")

heightM <- sample(heightM$Height, 30, F)
heightF <- heightF$Height

p1 <- hist(heightM,
           nclass = 30)

p2 <- hist(heightF,
           nclass = 10)

plot( p1, col=rgb(0,0,1,1/4),
      xlim=c(150,200),
      xlab = "height (cm)",
      ylab = "N",
      main = "Height comparison")

plot( p2, col=rgb(1,0,0,1/4),
      xlim=c(150,200),
      add=T)
```


```{r}
boxplot(data.frame(BMI_F,BMI_M), col = c("red", "blue"))
```



```{r echo=TRUE}
t.test(BMI_M, BMI_F, alternative = "less")
```

```{r echo=TRUE}
t.test(New_df$Height, mu=170, alternative = "greater") #alternative = "less", when H_1:\mu<170
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

