---
title: "Example1:"
output: 
  html_document
---

## Robotic vs LPS+LESS

### 1 Data Collection (from Ragic database)

```{r warning=FALSE, include=FALSE, massage=FALSE}
#packages
library(rlang)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(tableHTML)
load("Rdata/20240606_fullData.RData")
```

```{r echo=FALSE}
RobatLpsLess_kable
```

```{r eval=FALSE, include=FALSE}
RobatLpsLess_kable = kable(RobatLpsLess[1:10, -48], "html")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  scroll_box(width = "100%", height = "400px")%>%
  kable_paper(full_width = T)%>%
  row_spec(0, font_size = 14)%>%
  row_spec(1:10, font_size = 11)
```

### 2 Summarrize the original data table

<style>
.code_out{
  white-space: pre !important;
  overflow-y: scroll !important;
  height: 400px !important;
}

</style>

```{r, attr.output="code_out"}
summary(RobatLpsLess)
```

### 3 Check the missing value

```{r echo=FALSE}
RobatLpsLessMiss_kable
```

```{r eval=FALSE, include=FALSE}
RobatLpsLessMiss_kable = kable(missValue, "html")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  scroll_box(width = "100%", height = "400px")%>%
  kable_paper(full_width = T)%>%
  row_spec(0, font_size = 14)%>%
  row_spec(1:56, font_size = 11)
```
