---
title: "**【UTUC Database】**"
---

## UTUC 回朔

### 基本資料 retrospective (部分資料)

```{r warning=FALSE, include=FALSE, massage=FALSE}
#packages
library(rlang)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(tableHTML)
load("Rdata/20240606_fullData.RData")
```

```{r echo=FALSE}
Kable_UTUCall
```

```{r eval=FALSE, include=FALSE}
kable(UTUC_retr[101:110,-c(115,137,148,159,170,181,192)], "html")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  scroll_box(width = "100%", height = "550px")%>%
  kable_paper(full_width = T)%>%
  row_spec(0, font_size = 14)%>%
  row_spec(1:10, font_size = 11)
```

### Missing Value

```{r echo=FALSE}
missValue_utucALL_kable
```

### Variables

::: diary-box
-   診斷年齡
    -   $<70$
    -   $\geq 70$

------------------------------------------------------------------------

-   腫瘤大小
    -   $<2$ cm ($3$ cm)
    -   $\geq 2$cm ($3$ cm)

------------------------------------------------------------------------

-   腫瘤位置
    -   只有腎盂
    -   只有輸尿管
    -   兩者皆有

------------------------------------------------------------------------

-   病理分期 ($pT$)
    -   $T_\times,T_0,T_{is},T_a,T_1$ ( $T_\times,T_0,T_{is},T_a,T_1,T_2$ )
    -   $T_2, T_3, T_4$ ( $T_3, T_4$ )

------------------------------------------------------------------------

-   術後併發症 (取最嚴重)

------------------------------------------------------------------------

-   針對UTUC化療型態
    -   Neo-adjuvant and adjuvant
    -   o.w.
:::
